import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import Head from "next/head"
import {Inter} from 'next/font/google'
import NavBar from "@/app/components/navBar";
import ReduxProvider from "@/store/reduxPorvider";
import Footer from "@/app/components/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {

    return (

        <html lang='en'>
        <Head>
            <link rel="icon" href="/favicon.png" sizes="any" />
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>

        <body suppressHydrationWarning={true}
              className={inter.className}
        >
        <ReduxProvider>
            <NavBar/>
            {children}
            <Footer/>
        </ReduxProvider>
        </body>

        </html>


    )
}
