import styles from './page.module.css'
import PersonalizedRecommendations from "@/app/components/serverComponents/PersonalizedRecommendations";
import NavBar from "@/app/components/clientComponents/navBar";
import ImgSlider from "@/app/components/clientComponents/imgSlider";
import RecentlyAdded from "@/app/components/serverComponents/RecentlyAdded";
import {cache} from 'react'
import RecentlyAndMostPlayed from './components/serverComponents/recentlyAndMostPlayed'
import CommunityRecommendations from "@/app/components/serverComponents/CommunityRecommendations";
import {FaRobot} from "react-icons/fa";
import {Suspense} from "react";
import Loading from "@/app/components/serverComponents/loading";



export const metadata = {
    title: ' JoyStick games',
    description: 'Generated by create next app',
}


export const getGames = async () => {
    const data = await fetch(
        'https://www.freetogame.com/api/games', {
            method: 'GET',
            crossorigin: true,
            mode: 'no-cors'
        });
    if (!data.ok) {
        throw new Error('Failed to fetch data')
    }
    const games = await data.json();
    return games

};


export default async function Home() {

    return (

        <main className="mainPageContainer">
            <ImgSlider/>
            <Suspense fallback={<Loading/>}>
                <PersonalizedRecommendations/>
                <RecentlyAndMostPlayed/>
                <CommunityRecommendations/>
            </Suspense>
        </main>
    )
}

