import styles from './page.module.css'
import PersonalizedRecommendations from "@/app/components/PersonalizedRecommendations";
import NavBar from "@/app/components/navBar";
import ImgSlider from "@/app/components/imgSlider";
import RecentlyAdded from "@/app/components/RecentlyAdded";
import {cache} from 'react'
import RecentlyAndMostPlayed from './components/recentlyAndMostPlayed'
import CommunityRecommendations from "@/app/components/CommunityRecommendations";
import Footer from "@/app/components/Footer";
import {useSelector} from "react-redux";


export const metadata = {
    title: ' JoyStick games',
    description: 'Generated by create next app',
}


export const getGames = async () => {
    const data = await fetch(
        'https://www.freetogame.com/api/games', {
            method: 'GET',
            crossorigin: true,
            mode: 'no-cors'
        });
    if (!data.ok) {
        throw new Error('Failed to fetch data')
    }
    const games = await data.json();
    return games

};


export default async function Home() {

    return (

        <main className="mainPageContainer">
            <ImgSlider/>
            <PersonalizedRecommendations/>
            <RecentlyAndMostPlayed/>
            <CommunityRecommendations/>
        </main>
    )
}

